In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
df=pd.read_csv("boston.csv")

In [64]:
n_entries = len(df)
shuffled_indices = np.random.permutation(n_entries)
train_size = int(n_entries * 0.8)
train_indices = shuffled_indices[:train_size]
test_indices = shuffled_indices[train_size:]
train_df = df.iloc[train_indices]
test_df = df.iloc[test_indices]
train_df.to_csv("trainingdataset.csv")
test_df.to_csv("testingdataset.csv")

In [65]:
train_df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
342   0.02498   0.0   1.89     0  0.518  6.540  59.7  6.2669    1  422.0   
29    1.00245   0.0   8.14     0  0.538  6.674  87.3  4.2390    4  307.0   
335   0.03961   0.0   5.19     0  0.515  6.037  34.5  5.9853    5  224.0   
417  25.94060   0.0  18.10     0  0.679  5.304  89.1  1.6475   24  666.0   
92    0.04203  28.0  15.04     0  0.464  6.442  53.6  3.6659    4  270.0   
..        ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
144   2.77974   0.0  19.58     0  0.871  4.903  97.8  1.3459    5  403.0   
498   0.23912   0.0   9.69     0  0.585  6.019  65.3  2.4091    6  391.0   
359   4.26131   0.0  18.10     0  0.770  6.112  81.3  2.5091   24  666.0   
321   0.18159   0.0   7.38     0  0.493  6.376  54.3  4.5404    5  287.0   
484   2.37857   0.0  18.10     0  0.583  5.871  41.9  3.7240   24  666.0   

     PTRATIO       B  LSTAT  MEDV  
342     15.9  389.96   8.65  16.5  
29      21.0  380.23  11.98  21.0  
335     20.2  396.90   8.01  21.1  
417     20.2  127.36  26.64  10.4  
92      18.2  395.01   8.16  22.9  
..       ...     ...    ...   ...  
144     14.7  396.90  29.29  11.8  
498     19.2  396.90  12.92  21.2  
359     20.2  390.74  12.67  22.6  
321     19.6  396.90   6.87  23.1  
484     20.2  370.73  13.34  20.6  

[404 rows x 14 columns]

In [66]:
x=train_df.drop(columns='MEDV').to_numpy(dtype=float)
y=train_df['MEDV'].values.reshape(-1,1)

mean = np.mean(x, axis=0)
std = np.std(x, axis=0)
features_scaled = (x - mean) / std

bias = np.ones((x.shape[0], 1))
x_scaled = np.concatenate([bias, features_scaled], axis=1)

x = x_scaled

print(x.shape)
print(y.shape)
print(x)

(404, 14)
(404, 1)
[[ 1.         -0.41826249 -0.48553978 ... -1.25060977  0.35633616
  -0.57975603]
 [ 1.         -0.31196703 -0.48553978 ...  1.14949862  0.24575922
  -0.10698868]
 [ 1.         -0.41667154 -0.48553978 ...  0.77301103  0.43520604
  -0.67061822]
 ...
 [ 1.          0.0424193  -0.48553978 ...  0.77301103  0.3652005
  -0.00902788]
 [ 1.         -0.40123185 -0.48553978 ...  0.49064534  0.43520604
  -0.8324665 ]
 [ 1.         -0.16232018 -0.48553978 ...  0.77301103  0.13779613
   0.08609347]]


In [67]:
theta = np.linalg.inv(x.T@x) @ (x.T@y)
theta

array([[22.31633663],
       [-0.95692289],
       [ 1.25758452],
       [ 0.35979828],
       [ 0.59666761],
       [-2.06311883],
       [ 2.25716158],
       [ 0.31381456],
       [-2.96823994],
       [ 2.47763495],
       [-2.02488835],
       [-2.11385318],
       [ 0.51972449],
       [-4.07364704]])

In [68]:
yhat=x@theta
yhat

array([[22.05714796],
       [20.63639172],
       [20.36256388],
       [ 7.37922811],
       [29.0933027 ],
       [42.26984594],
       [38.63832143],
       [24.54272712],
       [28.38678794],
       [28.46076593],
       [29.62173604],
       [27.52300034],
       [28.24881749],
       [13.74938798],
       [33.24988622],
       [17.18550522],
       [23.72359925],
       [21.78096206],
       [34.01904537],
       [11.48086296],
       [28.75680174],
       [20.34383122],
       [13.3112927 ],
       [20.13798402],
       [20.756445  ],
       [16.69110976],
       [35.55821771],
       [13.23644683],
       [37.41992701],
       [20.41158877],
       [15.64070442],
       [43.98946615],
       [25.46626733],
       [16.21567997],
       [ 3.78808097],
       [22.5410698 ],
       [16.70070023],
       [22.43695727],
       [18.84782674],
       [28.48386543],
       [ 5.04229106],
       [17.29072956],
       [19.45197548],
       [34.03717946],
       [36.33838588],
       [16

In [69]:
y

array([[16.5],
       [21. ],
       [21.1],
       [10.4],
       [22.9],
       [50. ],
       [50. ],
       [21.4],
       [24.4],
       [22.8],
       [23. ],
       [23.9],
       [33.4],
       [13.4],
       [32. ],
       [ 7.2],
       [23.4],
       [22.5],
       [35.4],
       [10.8],
       [22. ],
       [20.5],
       [ 9.5],
       [21.7],
       [21.7],
       [17.1],
       [36.5],
       [14. ],
       [44.8],
       [27.9],
       [16.6],
       [50. ],
       [24.7],
       [10.2],
       [14.4],
       [17. ],
       [17.5],
       [19.8],
       [16.4],
       [31.2],
       [ 7.4],
       [19.4],
       [18.2],
       [34.9],
       [33.3],
       [23.2],
       [20.6],
       [18.2],
       [14.5],
       [19.3],
       [22.2],
       [20.1],
       [22.7],
       [43.5],
       [33.8],
       [20.4],
       [18.1],
       [15.7],
       [15.2],
       [34.6],
       [19.1],
       [32. ],
       [13.5],
       [41.3],
       [22.6],
       [27.1],
       [24

===========================================================================================================

TESTING

===========================================================================================================

In [70]:
x_test=test_df.drop(columns="MEDV").to_numpy(dtype=float)
y_test=test_df["MEDV"].values.reshape(-1,1)

mean_test = np.mean(x_test, axis=0)
std_test = np.std(x_test, axis=0)
features_scaled_test = (x_test - mean_test) / std_test

bias = np.ones((x_test.shape[0], 1))
x_test_scaled = np.concatenate([bias, features_scaled_test], axis=1)

x_test = x_test_scaled
print(x_test.shape)
print(y_test.shape)
yhat_test=x_test@theta
yhat_test

(102, 14)
(102, 1)


array([[19.87522648],
       [31.47125495],
       [31.35188327],
       [24.24672639],
       [18.47611225],
       [28.9134527 ],
       [25.70444828],
       [28.714982  ],
       [20.80153826],
       [26.06628008],
       [18.28328471],
       [16.4903421 ],
       [26.80128665],
       [20.00542851],
       [33.13050385],
       [23.0136482 ],
       [12.41120308],
       [35.80917136],
       [27.09993834],
       [15.30664375],
       [19.75065185],
       [ 5.44519875],
       [30.42680328],
       [18.44163425],
       [10.97756882],
       [29.68271044],
       [13.61716812],
       [20.27272863],
       [31.21171607],
       [24.8564634 ],
       [14.97299526],
       [29.20247151],
       [14.99294658],
       [16.95077341],
       [19.52934535],
       [21.56031276],
       [38.76851964],
       [24.10044316],
       [26.30738144],
       [16.79121211],
       [20.66803392],
       [12.56787626],
       [26.28348977],
       [23.57872341],
       [33.72256094],
       [18

In [71]:
y_test

array([[22. ],
       [50. ],
       [37.2],
       [19.1],
       [18.3],
       [24.1],
       [22.6],
       [32.7],
       [18.8],
       [36.2],
       [14.1],
       [13. ],
       [24.5],
       [18.7],
       [46.7],
       [18.9],
       [12.3],
       [41.7],
       [23.7],
       [16.2],
       [19.2],
       [13.8],
       [27.5],
       [19.9],
       [12.7],
       [31.5],
       [17.2],
       [19.7],
       [33.1],
       [21.6],
       [15.2],
       [28.7],
       [15.4],
       [15.6],
       [24.1],
       [22.4],
       [50. ],
       [29.8],
       [22. ],
       [12.7],
       [15.6],
       [10.9],
       [22. ],
       [24.2],
       [50. ],
       [20.4],
       [36.4],
       [13.9],
       [36.1],
       [20. ],
       [21.2],
       [15.6],
       [ 5.6],
       [11. ],
       [33.2],
       [33.4],
       [24.7],
       [19.5],
       [13.4],
       [13.1],
       [22.7],
       [24.8],
       [11.8],
       [18.8],
       [35.2],
       [30.3],
       [18

In [72]:
SS_res = np.sum((y - yhat) ** 2)
SS_tot = np.sum((y - np.mean(y)) ** 2)
R_sq = 1 - (SS_res / SS_tot)
print("R² Score:", R_sq)

R² Score: 0.7242829881012033


In [73]:
SS_res = np.sum((y_test - yhat_test) ** 2)
SS_tot = np.sum((y_test - np.mean(y_test)) ** 2)
R_sq = 1 - (SS_res / SS_tot)
print("R² Score:", R_sq)

R² Score: 0.7665309121460985


In [77]:
def ridge(alpha,x,y):
    n_features = x.shape[1]
    I = np.eye(n_features)
    I[0, 0] = 0
    beta = np.linalg.inv(x.T@x + alpha * I) @ x.T@y
    return beta
yhat_ridge=x_test @ ridge(0.01,x_test,y_test)
yhat_ridge

array([[19.91746622],
       [32.48594103],
       [33.67173706],
       [19.92393922],
       [19.37462545],
       [25.7014695 ],
       [24.67872136],
       [30.87316941],
       [18.0000729 ],
       [29.74012205],
       [17.02430135],
       [19.50648852],
       [26.67811421],
       [20.47141927],
       [39.41307188],
       [22.54710614],
       [15.08976882],
       [41.16772451],
       [27.91211886],
       [13.8715919 ],
       [19.6203366 ],
       [ 8.4693252 ],
       [34.37202748],
       [21.44567991],
       [12.26994514],
       [31.70543712],
       [14.37977247],
       [20.64080417],
       [33.11107489],
       [23.94693282],
       [17.38249562],
       [31.74074537],
       [16.67538765],
       [13.67158922],
       [19.64333485],
       [23.94018725],
       [45.04113203],
       [28.2881114 ],
       [26.49511447],
       [18.63000992],
       [20.10135609],
       [ 9.08618697],
       [25.66945495],
       [25.24400696],
       [39.14682765],
       [19

In [78]:
y_test

array([[22. ],
       [50. ],
       [37.2],
       [19.1],
       [18.3],
       [24.1],
       [22.6],
       [32.7],
       [18.8],
       [36.2],
       [14.1],
       [13. ],
       [24.5],
       [18.7],
       [46.7],
       [18.9],
       [12.3],
       [41.7],
       [23.7],
       [16.2],
       [19.2],
       [13.8],
       [27.5],
       [19.9],
       [12.7],
       [31.5],
       [17.2],
       [19.7],
       [33.1],
       [21.6],
       [15.2],
       [28.7],
       [15.4],
       [15.6],
       [24.1],
       [22.4],
       [50. ],
       [29.8],
       [22. ],
       [12.7],
       [15.6],
       [10.9],
       [22. ],
       [24.2],
       [50. ],
       [20.4],
       [36.4],
       [13.9],
       [36.1],
       [20. ],
       [21.2],
       [15.6],
       [ 5.6],
       [11. ],
       [33.2],
       [33.4],
       [24.7],
       [19.5],
       [13.4],
       [13.1],
       [22.7],
       [24.8],
       [11.8],
       [18.8],
       [35.2],
       [30.3],
       [18

In [79]:
SS_res = np.sum((y_test - yhat_ridge) ** 2)
SS_tot = np.sum((y_test - np.mean(y_test)) ** 2)
R_sq = 1 - (SS_res / SS_tot)
print("R² Score:", R_sq)

R² Score: 0.8376328712044296


In [ ]:
def ridge(alpha,x,y):
    n_features = x.shape[1]
    I = np.eye(n_features)
    I[0, 0] = 0
    beta = np.linalg.inv(x.T@x + alpha * I) @ x.T@y
    return beta
yhat_ridge=x_test @ ridge(0.01,x_test,y_test)
yhat_ridge