In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("insurance.csv")
df['smoker']=df['smoker'].map({'yes': 1, 'no': 0})
df['sex']=df['sex'].map({'male': 1, 'female': 0})
df = pd.get_dummies(df, columns=['region'], drop_first=False)
df=df.sort_values(by='charges',ascending=False)
print(df.head())
df.shape

      age  sex     bmi  children  smoker      charges  region_northeast  \
543    54    0  47.410         0       1  63770.42801             False   
1300   45    1  30.360         0       1  62592.87309             False   
1230   52    1  34.485         3       1  60021.39897             False   
577    31    0  38.095         1       1  58571.07448              True   
819    33    0  35.530         0       1  55135.40209             False   

      region_northwest  region_southeast  region_southwest  
543              False              True             False  
1300             False              True             False  
1230              True             False             False  
577              False             False             False  
819               True             False             False  


(1338, 10)

In [3]:
n_entries = len(df)
shuffled_indices = np.random.permutation(n_entries)
train_size = int(n_entries * 0.8)
train_indices = shuffled_indices[:train_size]
test_indices = shuffled_indices[train_size:]
train_df = df.iloc[train_indices]
test_df = df.iloc[test_indices]

In [4]:
train_df.head()

age  sex    bmi  children  smoker     charges  region_northeast  \
766    47    1  32.30         1       0   8062.7640             False   
248    19    1  20.90         1       0   1832.0940             False   
1330   57    0  25.74         2       0  12629.1656             False   
776    40    1  32.30         2       0   6986.6970             False   
1083   32    1  31.50         1       0   4076.4970             False   

      region_northwest  region_southeast  region_southwest  
766              False             False              True  
248              False             False              True  
1330             False              True             False  
776               True             False             False  
1083             False             False              True

In [6]:
# plt.figure(figsize=(10, 10))
# plt.scatter(df['region'], df['charges'])
# plt.title('Medical Charges vs Age')
# plt.xlabel('Age')
# plt.ylabel('Medical Charges')
# plt.grid(True)
# plt.show()

In [29]:
x = train_df.drop(columns='charges').to_numpy(dtype=float)
y = train_df['charges'].to_numpy().reshape(-1, 1).astype(float)


mean = np.mean(x, axis=0)
std = np.std(x, axis=0)
features_scaled = (x - mean) / std

bias = np.ones((features_scaled.shape[0], 1))
x_scaled = np.concatenate([bias, features_scaled], axis=1)

x = x_scaled

print(x.shape)
print(y.shape)
print(x)

(1070, 10)
(1070, 1)
[[ 1.          0.56056989  0.97052758 ... -0.56079971 -0.60110162
   1.75612342]
 [ 1.         -1.43026392  0.97052758 ... -0.56079971 -0.60110162
   1.75612342]
 [ 1.          1.27158197 -1.03036743 ... -0.56079971  1.66361222
  -0.56943606]
 ...
 [ 1.          0.48946869 -1.03036743 ... -0.56079971  1.66361222
  -0.56943606]
 [ 1.         -0.86145426  0.97052758 ... -0.56079971 -0.60110162
  -0.56943606]
 [ 1.          0.41836748  0.97052758 ... -0.56079971 -0.60110162
  -0.56943606]]


(X'X)

In [20]:
xt_x = x.T@x
xt_x=xt_x.astype(float)
xt_x

array([[ 1.07000000e+03,  6.83897383e-14, -7.10542736e-15,
        -1.03117515e-12, -8.52651283e-14, -3.99680289e-15,
        -2.39808173e-13,  4.70734562e-14, -1.63424829e-13,
         1.40332190e-13],
       [ 6.83897383e-14,  1.07000000e+03, -5.54630182e+01,
         1.00769169e+02,  6.28782821e+01, -4.03277385e+01,
         2.03387786e+01,  8.22173633e+00, -2.24018842e+00,
        -2.63506226e+01],
       [-7.10542736e-15, -5.54630182e+01,  1.07000000e+03,
         3.75470062e+01,  2.67345255e+01,  1.09703288e+02,
        -4.65252247e+00,  8.06510335e-01,  1.24763227e+01,
        -8.92370756e+00],
       [-1.03117515e-12,  1.00769169e+02,  3.75470062e+01,
         1.07000000e+03,  2.24777581e+01,  1.45290910e+01,
        -1.63635876e+02, -1.23080841e+02,  2.84260555e+02,
        -4.90014653e+00],
       [-8.52651283e-14,  6.28782821e+01,  2.67345255e+01,
         2.24777581e+01,  1.07000000e+03,  1.14686001e+01,
        -1.89154182e+01,  3.07253444e-01, -6.76920465e+00,
         2.

(X'Y)

theta=((X'X)^-1)(X'Y)

In [22]:
theta = np.linalg.inv(xt_x) @ xt_y
theta

array([[13326.10391927],
       [ 3577.19085044],
       [  -93.06403699],
       [ 2280.80256001],
       [  602.95936123],
       [ 9774.39274302],
       [-2304.        ],
       [-3584.        ],
       [-3072.        ],
       [-2816.        ]])

In [23]:
y[:10]

array([[ 8062.764  ],
       [ 1832.094  ],
       [12629.1656 ],
       [ 6986.697  ],
       [ 4076.497  ],
       [ 4350.5144 ],
       [ 7789.635  ],
       [38245.59327],
       [ 2803.69785],
       [ 2395.17155]])

In [36]:
yhat=x @ theta
yhat[:10]

array([[11061.97803719],
       [ -308.13481707],
       [11430.11405596],
       [ 7921.26254469],
       [ 6948.69742309],
       [ 5637.34378575],
       [ 9447.24762109],
       [31204.85881196],
       [-1774.66519603],
       [ 2546.30757944]])

In [37]:
yhat = x @ theta
SS_res = np.sum((y - yhat) ** 2)
SS_tot = np.sum((y - np.mean(y)) ** 2)
R_sq = 1 - (SS_res / SS_tot)
print("R² Score:", R_sq)

R² Score: 0.753038849450587


==========================================================================================================

TESTING

==========================================================================================================

In [15]:
test_df.head()

age  sex     bmi  children  smoker      charges  region_northeast  \
1213   52    0  33.300         2       0  10806.83900             False   
232    19    0  17.800         0       0   1727.78500             False   
81     45    0  38.285         0       0   7935.29115              True   
537    46    0  30.200         2       0   8825.08600             False   
120    44    1  37.100         2       0   7740.33700             False   

      region_northwest  region_southeast  region_southwest  
1213             False             False              True  
232              False             False              True  
81               False             False             False  
537              False             False              True  
120              False             False              True

In [31]:
x_test=test_df.drop(columns='charges').to_numpy(dtype=float)
y_test=test_df['charges'].to_numpy().reshape(-1, 1).astype(float)

features_scaled = (x_test - mean) / std

bias = np.ones((features_scaled.shape[0], 1))
x_test_scaled = np.concatenate([bias, features_scaled], axis=1)

x_test = x_test_scaled



print(x_test.shape)
print(y_test.shape)

(268, 10)
(268, 1)


In [35]:
yhat_test=x_test @ theta
yhat_test[:10]

array([[13384.2663625 ],
       [-1768.90963702],
       [13709.51503014],
       [10702.91143166],
       [12579.48773907],
       [33176.1410662 ],
       [13038.154082  ],
       [13945.51511271],
       [11602.32099333],
       [24653.14811734]])

In [34]:
y_test[:10]

array([[10806.839  ],
       [ 1727.785  ],
       [ 7935.29115],
       [ 8825.086  ],
       [ 7740.337  ],
       [37701.8768 ],
       [10560.4917 ],
       [10381.4787 ],
       [ 5709.1644 ],
       [17748.5062 ]])

In [39]:
SS_res = np.sum((y_test - yhat_test) ** 2)
SS_tot = np.sum((y_test - np.mean(y_test)) ** 2)
R_sq = 1 - (SS_res / SS_tot)
print("R² Score:", R_sq)

R² Score: 0.6966883742455382
